# Generated by Django 4.2.7 on 2024-03-03 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Book',
            new_name='book',
        ),
    ]
